logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    com.youngzy: debug
spring:
  rabbitmq:
    host: localhost # rabbitMQ的ip地址
    port: 5672 # 端口
    username: advanced
    password: advanced
    virtual-host: advanced
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true