logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    com.youngzy: debug
spring:
  rabbitmq:
#    host: 192.168.150.101 # rabbitMQ的ip地址
#    port: 5672 # 端口
    addresses: localhost
    username: advanced
    password: advanced
    virtual-host: advanced
    listener:
      simple:
        prefetch: 1
#        acknowledge-mode: none
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 3
          max-attempts: 4